### ISSUE TITLE
explain what "core" stands for

### ISSUE THREAD

**Issue by helix123** [eddelbuettel/ctv-finance#6]
In the list of CRAN packages, some packages are marked with "(core)". It seems unclear what that means. They are not (necessarily) core packages of R in the sense of the recommended packages. Rather, it seems they are "core" to the task view. However, that does not seem to be explained somewhere? (Also true for other task views).

**Comment by eddelbuettel** [comment]
IIRC that is in fact explained in the Task View package, see eg page 2 of the [vignette of package ctv](https://cloud.r-project.org/web/packages/ctv/vignettes/ctv-howto.pdf).

These are packages that will be installed by default when someone.  It really is a Task View thing.  Not sure where to explain that better.  

Thoughts?

**Comment by helix123** [comment]
People looking at the Task Views will likely not look at the package helping to produce the Task Views, neither did I. Why not put an explanatory sentence at the top of the Task View or right before/after the pure list of packages?
